version: '2.1'
services:
  docker:
    image: docker:stable-dind
    privileged: true
    ports: 
      - "2375:2375"
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      ADVERTISED_HOST: kafka
  scylla:
    image: scylladb/scylla
    ports:
      - "9042:9042"
    healthcheck:
      test: >
        cqlsh -e "CREATE KEYSPACE IF NOT EXISTS furan WITH REPLICATION = { 'class': 'SimpleStrategy', 'replication_factor': 1 } AND DURABLE_WRITES = true;"
      interval: 10s
      timeout: 5s
      retries: 20
  vault:
    image: quay.io/dollarshaveclub/vault-dev:master
    ports:
      - "8200:8200"
    volumes:
      - "$PWD/local_dev_secrets.json:/opt/secrets.json"
  furan:
    build: .
    image: furan:local
    environment:
      - VAULT_TOKEN=root
      - VAULT_ADDR=http://vault:8200
      - DOCKER_HOST=tcp://docker:2375
    # delay startup to wait for other services to be ready and for network links to come up
    command: /dc-run.sh
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
    ulimits:
      nofile: 65535
    depends_on:
      - kafka
      - scylla
      - vault
      - docker
    healthcheck:
      test: echo 'GET /' |nc localhost 4002
      interval: 25s
      timeout: 5s
      retries: 10
