{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: furan
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.httpExternalPort }}
    targetPort: {{ .Values.service.httpInternalPort }}
    protocol: TCP
    name: {{ .Values.service.httpServiceName }}
  - port: {{ .Values.service.grpcExternalPort }}
    targetPort: {{ .Values.service.grpcInternalPort }}
    protocol: TCP
    name: {{ .Values.service.grpcServiceName }}
  selector:
    appsel: furan
{{- end -}}
