# Default values for furan.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 8
maxSurge: 25%
maxUnavailable: 25%
env: qa
image:
  repository: quay.io/dollarshaveclub/furan
  tag: master
  pullPolicy: Always
