#cloud-config

---

write-files:
- path: /etc/vault-env.sh
  permissions: "0755"
  content: |
    VAULT_ADDR=https://vault.domain.io:8200
    VAULT_TOKEN={{ VAULT TOKEN }}
- path: /opt/docker-api-version.sh
  permissions: "0755"
  content: |
    #!/bin/bash
    DAPIVERSION=$(curl --silent -XGET --unix-socket /var/run/docker.sock http:/1/version |jq -r '.ApiVersion')
    echo "DOCKER_API_VERSION=${DAPIVERSION}" >> /etc/docker-env.sh
- path: /etc/docker-env.sh
  permissions: "0644"
  content: |
    DOCKER_HOST=unix:///var/run/docker.sock
coreos:
  etcd2:
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
  units:
  - name: docker.service
    command: restart
  - name: docker.service
    command: ""
    drop-ins:
    - name: 10-ramdisk.conf
      content: |
        [Unit]
        After=var-lib-docker.mount
        Requires=var-lib-docker.mount

        [Service]
        Environment=DOCKER_RAMDISK=1
    - name: 20-docker-opts.conf
      content: |
        [Service]
        Environment="DOCKER_OPTS=--storage-driver=overlay2"
  - name: var-lib-docker.mount
    command: ""
    enable: true
    content: |
      [Unit]
      Description=Mount data volume
      Before=docker.service

      [Mount]
      What=tmpfs
      Where=/var/lib/docker
      Type=tmpfs
      Options=rw,size=15G
  - name: furan.service
    command: start
    content: |
      [Unit]
      Description=Furan
      Requires=docker.service
      After=docker.service

      [Service]
      Restart=on-failure
      TimeoutStartSec=1200
      EnvironmentFile=/etc/vault-env.sh
      ExecStartPre=/usr/bin/docker pull quay.io/dollarshaveclub/furan:master
      ExecStartPre=-/usr/bin/docker rm furan
      ExecStartPre=/opt/docker-api-version.sh
      ExecStart=/usr/bin/docker run --name furan --env-file /etc/vault-env.sh --env-file /etc/docker-env.sh -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/opt/docker-storage:ro --net=host quay.io/dollarshaveclub/furan:master /go/bin/furan -z -f "kafka-broker1:9092,kafka-broker2:9092" server --log-to-sumo=false --s3-error-logs --s3-error-log-bucket furan-errorlogs --docker-storage-path /opt/docker-storage
      ExecStop=/usr/bin/docker stop furan
  update:
    group: beta
    reboot-strategy: "off"
